### ISSUE TITLE
It doesn't run

### ISSUE THREAD

**Issue by DRSchlaubi** [MoMMde/logsearcher#1]
I tried running this but there is no script

**Comment by NyCodeGHG** [comment]
I also tried this and I have the same issue

**Comment by MoMMde** [comment]
yup, having the same issue :(

**Comment by MoMMde** [comment]
Sry my mistake, i forgot to Push it, i will do this tomorrow

**Comment by DRSchlaubi** [comment]
> @MoMMde is it fixed now? I still can't find a script

Me neither

**Comment by MoMMde** [comment]
Should work now :)
